//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicApiWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int image_id { get; set; }
        public string link { get; set; }
        public Nullable<int> chapter_id { get; set; }
    
        public virtual Chapter Chapter { get; set; }
    }
}
